#!/usr/bin/env bash
# Runtime profile import, selection, drift, and removal tests.
set -euo pipefail

pass() { printf '  PASS %s\n' "$*"; }
fail() { printf '  FAIL %s\n' "$*" >&2; exit 1; }

TEST_TMP_DIR=$(mktemp -d)
cleanup() { rm -rf "${TEST_TMP_DIR:?}"; }
trap cleanup EXIT

# shellcheck source=../src/common.sh
source src/common.sh
# shellcheck source=../src/lock.sh
source src/lock.sh
# shellcheck source=../src/state.sh
source src/state.sh
# shellcheck source=../src/elf.sh
source src/elf.sh
# shellcheck source=../src/runtime.sh
source src/runtime.sh
# shellcheck source=../src/wrapper.sh
source src/wrapper.sh
# shellcheck source=../src/resolver.sh
source src/resolver.sh
# shellcheck source=../src/patch.sh
source src/patch.sh

CLI_STORAGE="${TEST_TMP_DIR}/state"
REGISTRY_FILE="${CLI_STORAGE}/registry.json"
APPS_DIR="${CLI_STORAGE}/apps"
BIN_DIR="${CLI_STORAGE}/bin"
CACHE_DIR="${CLI_STORAGE}/cache"
LOCK_DIR="${CLI_STORAGE}/locks"
LOG_DIR="${CLI_STORAGE}/logs"
TMP_DIR="${CLI_STORAGE}/tmp"
PROFILE_STATE_DIR="${CLI_STORAGE}/profiles"
RUNTIME_ROOT="${TEST_TMP_DIR}/managed-runtimes"

if [[ -x "${PREFIX:-/nonexistent}/glibc/lib/ld-linux-aarch64.so.1" ]]; then
    source_loader="${PREFIX}/glibc/lib/ld-linux-aarch64.so.1"
    source_libc="${PREFIX}/glibc/lib/libc.so.6"
    fixture_sysroot="${PREFIX}/glibc"
else
    source_loader=$(find /lib /usr/lib -name ld-linux-aarch64.so.1 -type f -print -quit 2>/dev/null)
    source_libc=$(find /lib /usr/lib -name libc.so.6 -type f -print -quit 2>/dev/null)
    fixture_sysroot=/
fi
[[ -n "$source_loader" && -n "$source_libc" ]] || fail "AArch64 glibc fixture is unavailable"

GLIBC_PREFIX="${TEST_TMP_DIR}/fake-glibc"
GLIBC_LIB_DIR="${GLIBC_PREFIX}/lib"
GLIBC_INTERPRETER="${GLIBC_LIB_DIR}/ld-linux-aarch64.so.1"
mkdir -p "$GLIBC_LIB_DIR" "${GLIBC_PREFIX}/etc" "${GLIBC_PREFIX}/share/locale"
cp "$source_loader" "$GLIBC_INTERPRETER"
cp "$source_libc" "${GLIBC_LIB_DIR}/libc.so.6"
printf 'hosts: files dns\n' >"${GLIBC_PREFIX}/etc/nsswitch.conf"

cmd_runtime_import_system >/dev/null
[[ -f "${PROFILE_STATE_DIR}/system.json" ]] || fail "system profile manifest was not created"
jq -e '
    .profile_id == "system"
    and .kind == "system"
    and .immutable == false
    and (.files | length) == 3
' "${PROFILE_STATE_DIR}/system.json" >/dev/null || fail "system profile manifest is incomplete"
runtime_profile_verify system >/dev/null || fail "fresh system profile did not verify"
selected=$(runtime_profile_select system 2>/dev/null)
jq -e '.profile_id == "system" and .files == null' <<<"$selected" >/dev/null \
    || fail "explicit system profile selection was not compact and valid"
if runtime_profile_select >/dev/null 2>&1; then
    fail "automatic selection silently chose the mutable system profile"
fi
pass "explicit-only mutable system profile"

if [[ -x "${PREFIX:-/nonexistent}/glibc/bin/bash" ]]; then
    dry_run_target="${PREFIX}/glibc/bin/bash"
else
    dry_run_target="/bin/bash"
fi
state_before=$(find "$CLI_STORAGE" -type f -print0 | LC_ALL=C sort -z | xargs -0 sha256sum)
cmd_patch "$dry_run_target" --runtime system --dry-run --no-verify >/dev/null
state_after=$(find "$CLI_STORAGE" -type f -print0 | LC_ALL=C sort -z | xargs -0 sha256sum)
[[ "$state_before" == "$state_after" ]] || fail "patch --dry-run changed state files"
[[ ! -e "${LOCK_DIR}/target-$(_sha256_text "$(realpath "$dry_run_target")").lock" ]] \
    || fail "patch --dry-run acquired a target mutation lock"
pass "mutation-free patch dry run"

printf 'drift\n' >>"${GLIBC_LIB_DIR}/libc.so.6"
if runtime_profile_verify system >/dev/null 2>&1; then
    fail "runtime drift was not detected"
fi
cp "$source_libc" "${GLIBC_LIB_DIR}/libc.so.6"
runtime_profile_verify system >/dev/null || fail "restored profile did not verify"
pass "runtime profile drift detection"

cmd_runtime_remove system >/dev/null
[[ ! -e "${PROFILE_STATE_DIR}/system.json" ]] || fail "unreferenced system profile was not removed"
pass "unreferenced profile removal"

# Build a fully signed local managed-profile fixture. This key is ephemeral and
# exists only inside the test directory; production key material is never
# generated by the repository or CI.
command -v gpg >/dev/null 2>&1 || fail "gpg is required for signed profile fixtures"
fixture_gnupg="${TEST_TMP_DIR}/gnupg"
fixture_keyring="${TEST_TMP_DIR}/fixture-release.gpg"
mkdir -m 700 "$fixture_gnupg"
GNUPGHOME="$fixture_gnupg" gpg --batch --pinentry-mode loopback --passphrase '' \
    --quick-gen-key 'glibcx runtime fixture <fixture@invalid>' ed25519 sign 1d >/dev/null 2>&1
fixture_fingerprint=$(GNUPGHOME="$fixture_gnupg" gpg --batch --with-colons --list-keys \
    | awk -F: '$1 == "fpr" {print $10; exit}')
GNUPGHOME="$fixture_gnupg" gpg --batch --export "$fixture_fingerprint" >"$fixture_keyring"
RUNTIME_RELEASE_KEYRING="$fixture_keyring"
RUNTIME_RELEASE_PRIMARY_FINGERPRINT="$fixture_fingerprint"
RUNTIME_TEST_ALLOW_LOCAL_ASSETS=true

fixture_profile_id="fixture-1"
fixture_final_dir="${RUNTIME_ROOT}/${fixture_profile_id}"
fixture_payload="${TEST_TMP_DIR}/profile-payload"
fixture_bundle="${TEST_TMP_DIR}/${fixture_profile_id}.tar.xz"
fixture_bundle_signature="${fixture_bundle}.asc"
fixture_catalog="${TEST_TMP_DIR}/catalog.json"
fixture_catalog_signature="${fixture_catalog}.asc"
mkdir -p "${fixture_payload}/lib"
cp "$source_loader" "${fixture_payload}/lib/ld-linux-aarch64.so.1"
cp "$source_libc" "${fixture_payload}/lib/libc.so.6"
fixture_audit="${fixture_payload}/lib/glibcx-loader-audit.so"
bash profiles/build-loader-audit.sh \
    "$fixture_sysroot" profiles/loader-audit.c "$fixture_audit"
chmod 755 "${fixture_payload}/lib/ld-linux-aarch64.so.1" "${fixture_payload}/lib/libc.so.6"
loader_hash=$(_sha256_file "${fixture_payload}/lib/ld-linux-aarch64.so.1")
libc_hash=$(_sha256_file "${fixture_payload}/lib/libc.so.6")
audit_hash=$(_sha256_file "$fixture_audit")
provided_versions=$(LC_ALL=C strings "$source_libc" 2>/dev/null \
    | grep -oE 'GLIBC(_ABI)?_[A-Za-z0-9_.]+' | LC_ALL=C sort -uV | jq -Rsc 'split("\n") | map(select(length > 0))')
jq -n \
    --arg id "$fixture_profile_id" \
    --arg prefix "$fixture_final_dir" \
    --arg loader "${fixture_final_dir}/lib/ld-linux-aarch64.so.1" \
    --arg library_dir "${fixture_final_dir}/lib" \
    --arg loader_hash "$loader_hash" \
    --arg libc_hash "$libc_hash" \
    --arg audit_hash "$audit_hash" \
    --arg termux_prefix "${PREFIX:-/data/data/com.termux/files/usr}" \
    --argjson versions "$provided_versions" \
    '{
        schema: 1,
        compatibility_schema: 2,
        profile_id: $id,
        kind: "managed",
        created_at: "2026-08-09T00:00:00Z",
        architecture: "aarch64",
        elf_class: "ELF64",
        endianness: "little-endian",
        prefix: $prefix,
        loader: $loader,
        library_dirs: [$library_dir],
        glibc_version: "fixture",
        termux: {package_name: "com.termux", prefix: $termux_prefix, package_revision: "fixture-1"},
        android: {min_api: 31, max_api: 36},
        kernel_min: "4.14",
        build: {
            source_url: "https://example.invalid/glibc.tar.xz",
            source_sha256: "0000000000000000000000000000000000000000000000000000000000000000",
            termux_glibc_commit: "0000000000000000000000000000000000000000",
            corresponding_source_url: "https://example.invalid/source.tar.xz",
            toolchain: "fixture clang",
            licenses: ["LGPL-2.1-or-later"]
        },
        provided_versions: $versions,
        allowed_tunables: [],
        loader_audit: {
            path: ($prefix + "/lib/glibcx-loader-audit.so"),
            sha256: $audit_hash,
            protocol: 1,
            fd: 198
        },
        loader_policy: {glibc_hwcaps_mask: ""},
        files: [
            {path: "lib/ld-linux-aarch64.so.1", type: "file", sha256: $loader_hash, mode: "755"},
            {path: "lib/libc.so.6", type: "file", sha256: $libc_hash, mode: "755"},
            {path: "lib/glibcx-loader-audit.so", type: "file", sha256: $audit_hash, mode: "755"}
        ]
    }' >"${fixture_payload}/profile.json"
GNUPGHOME="$fixture_gnupg" gpg --batch --yes --armor --detach-sign \
    --output "${fixture_payload}/profile.json.asc" "${fixture_payload}/profile.json"
tar -cJf "$fixture_bundle" -C "$fixture_payload" .
GNUPGHOME="$fixture_gnupg" gpg --batch --yes --armor --detach-sign \
    --output "$fixture_bundle_signature" "$fixture_bundle"
bundle_hash=$(_sha256_file "$fixture_bundle")
profile_hash=$(_sha256_file "${fixture_payload}/profile.json")
catalog_published=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
catalog_expiry=$(date -u -d "${catalog_published} +180 days" '+%Y-%m-%dT%H:%M:%SZ')
jq -n \
    --arg published "$catalog_published" \
    --arg expires "$catalog_expiry" \
    --arg signing_fingerprint "$fixture_fingerprint" \
    --arg id "$fixture_profile_id" \
    --arg bundle "$fixture_bundle" \
    --arg signature "$fixture_bundle_signature" \
    --arg bundle_hash "$bundle_hash" \
    --arg profile_hash "$profile_hash" \
    '{
        schema: 1,
        catalog_version: 2,
        issued_at: $published,
        published_at: $published,
        expires_at: $expires,
        min_glibcx_version: "0.3.0",
        signing_subkey_fingerprint: $signing_fingerprint,
        profile_compatibility_schema: 2,
        profiles: [{
            profile_id: $id,
            architecture: "aarch64",
            priority: 100,
            security_state: "recommended",
            manifest_sha256: $profile_hash,
            bundle: {url: $bundle, signature_url: $signature, sha256: $bundle_hash}
        }]
    }' >"$fixture_catalog"
GNUPGHOME="$fixture_gnupg" gpg --batch --yes --armor --detach-sign \
    --output "$fixture_catalog_signature" "$fixture_catalog"
RUNTIME_CATALOG_URL="$fixture_catalog"
RUNTIME_CATALOG_SIGNATURE_URL="$fixture_catalog_signature"

cmd_runtime_install recommended >/dev/null
[[ -f "${fixture_final_dir}/manifest.json" ]] || fail "signed managed profile was not installed"
jq -e '
    .kind == "managed"
    and .signature_verified == true
    and .recommended == true
    and .catalog_version == 2
' "${fixture_final_dir}/manifest.json" >/dev/null || fail "managed profile trust state is incomplete"
runtime_profile_verify "$fixture_profile_id" >/dev/null || fail "installed managed profile did not verify"
managed_selected=$(runtime_profile_select)
jq -e --arg id "$fixture_profile_id" '.profile_id == $id' <<<"$managed_selected" >/dev/null \
    || fail "automatic selection did not choose the signed recommended profile"
if runtime_profile_select '' '{"version_requirements":["GLIBC_999.0"]}' >/dev/null 2>&1; then
    fail "managed profile selection ignored target symbol requirements"
fi
pass "signed managed profile install and selection"

jq '.loader = (.prefix + "/../escape/ld.so")' \
    "${fixture_payload}/profile.json" >"${TEST_TMP_DIR}/unsafe-profile.json"
if _runtime_profile_manifest_validate "${TEST_TMP_DIR}/unsafe-profile.json" \
    "$fixture_profile_id" "$fixture_final_dir" >/dev/null 2>&1; then
    fail "managed profile accepted a non-canonical loader path"
fi
pass "managed profile canonical-path enforcement"

jq '.compatibility_schema = 1' \
    "${fixture_payload}/profile.json" >"${TEST_TMP_DIR}/wrong-profile-schema.json"
if _runtime_profile_manifest_validate "${TEST_TMP_DIR}/wrong-profile-schema.json" \
    "$fixture_profile_id" "$fixture_final_dir" >/dev/null 2>&1; then
    fail "managed profile accepted an incompatible schema"
fi
jq '.min_glibcx_version = "99.0.0"' \
    "$fixture_catalog" >"${TEST_TMP_DIR}/future-client-catalog.json"
if _runtime_catalog_validate "${TEST_TMP_DIR}/future-client-catalog.json" >/dev/null 2>&1; then
    fail "catalog minimum client version was ignored"
fi
jq 'del(.issued_at)' "$fixture_catalog" >"${TEST_TMP_DIR}/missing-issued-at-catalog.json"
if _runtime_catalog_validate "${TEST_TMP_DIR}/missing-issued-at-catalog.json" >/dev/null 2>&1; then
    fail "catalog without issued_at was accepted"
fi
pass "catalog client and compatibility gates"

catalog_state_before=$(_sha256_file "${PROFILE_STATE_DIR}/catalog-state.json")
jq '.catalog_version = 3
    | .signing_subkey_fingerprint = "0000000000000000000000000000000000000000"' \
    "$fixture_catalog" >"${fixture_catalog}.wrong-signer"
GNUPGHOME="$fixture_gnupg" gpg --batch --yes --armor --detach-sign \
    --output "${fixture_catalog}.wrong-signer.asc" "${fixture_catalog}.wrong-signer"
RUNTIME_CATALOG_URL="${fixture_catalog}.wrong-signer"
RUNTIME_CATALOG_SIGNATURE_URL="${fixture_catalog}.wrong-signer.asc"
if _runtime_catalog_refresh >/dev/null 2>&1; then
    fail "catalog accepted a signing-subkey field that did not match its signature"
fi
[[ "$catalog_state_before" == "$(_sha256_file "${PROFILE_STATE_DIR}/catalog-state.json")" ]] \
    || fail "signer mismatch changed accepted catalog state"
RUNTIME_CATALOG_URL="$fixture_catalog"
RUNTIME_CATALOG_SIGNATURE_URL="$fixture_catalog_signature"
pass "exact catalog signing-subkey binding"

cached_catalog=$(jq -r '.catalog' "${PROFILE_STATE_DIR}/catalog-state.json")
cp "${cached_catalog}.asc" "${cached_catalog}.asc.clean"
printf 'not an OpenPGP signature\n' >"${cached_catalog}.asc"
if _runtime_catalog_cached >/dev/null 2>&1; then
    fail "offline catalog cache accepted a corrupted signature"
fi
mv "${cached_catalog}.asc.clean" "${cached_catalog}.asc"
pass "offline catalog signature revalidation"

printf 'unsafe\n' >"${TEST_TMP_DIR}/unsafe-member"
tar -cJf "${TEST_TMP_DIR}/unsafe-runtime.tar.xz" -C "$TEST_TMP_DIR" \
    --transform='s|^unsafe-member$|../escape|' unsafe-member
if _runtime_archive_validate "${TEST_TMP_DIR}/unsafe-runtime.tar.xz" >/dev/null 2>&1; then
    fail "runtime archive traversal was accepted"
fi
pass "runtime archive traversal rejection"

mode_escape_root="${TEST_TMP_DIR}/mode-escape"
mode_escape_target="${TEST_TMP_DIR}/outside-mode-target"
mkdir -p "${mode_escape_root}/lib"
printf 'outside\n' >"$mode_escape_target"
chmod 600 "$mode_escape_target"
ln -s "$mode_escape_target" "${mode_escape_root}/lib/file.so"
jq -n '{files: [{path: "lib/file.so", type: "file", mode: "755",
    sha256: "0000000000000000000000000000000000000000000000000000000000000000"}]}' \
    >"${mode_escape_root}/profile.json"
if _runtime_apply_inventory_modes "$mode_escape_root" "${mode_escape_root}/profile.json" \
    >/dev/null 2>&1; then
    fail "managed profile mode application followed a symlink"
fi
[[ "$(stat -c '%a' "$mode_escape_target")" == 600 ]] \
    || fail "managed profile mode application changed an out-of-tree file"
pass "profile mode application rejects symlinks before chmod"

catalog_state_before=$(_sha256_file "${PROFILE_STATE_DIR}/catalog-state.json")
jq '.catalog_version = 1' "$fixture_catalog" >"${fixture_catalog}.rollback"
GNUPGHOME="$fixture_gnupg" gpg --batch --yes --armor --detach-sign \
    --output "${fixture_catalog}.rollback.asc" "${fixture_catalog}.rollback"
RUNTIME_CATALOG_URL="${fixture_catalog}.rollback"
RUNTIME_CATALOG_SIGNATURE_URL="${fixture_catalog}.rollback.asc"
if _runtime_catalog_refresh >/dev/null 2>&1; then
    fail "signed catalog rollback was accepted"
fi
[[ "$catalog_state_before" == "$(_sha256_file "${PROFILE_STATE_DIR}/catalog-state.json")" ]] \
    || fail "failed rollback changed accepted catalog state"
pass "signed catalog rollback rejection"

printf 'drift\n' >>"${fixture_final_dir}/lib/libc.so.6"
if runtime_profile_verify "$fixture_profile_id" >/dev/null 2>&1; then
    fail "managed runtime drift was not detected"
fi
cp "$source_libc" "${fixture_final_dir}/lib/libc.so.6"
chmod 755 "${fixture_final_dir}/lib/libc.so.6"
runtime_profile_verify "$fixture_profile_id" >/dev/null || fail "restored managed profile did not verify"
cmd_runtime_remove "$fixture_profile_id" >/dev/null
[[ ! -e "$fixture_final_dir" ]] || fail "managed profile removal left its runtime directory"
pass "managed profile drift and removal"

printf '\nAll runtime profile tests passed.\n'
